/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "cashier.payment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "cashier.webhook": [],
    "register": [],
    "register.store": [],
    "login": [],
    "login.store": [],
    "logout.store": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.notice": [],
    "verification.send": [],
    "dashboard": [],
    "budgets.create": [],
    "budgets.store": [],
    "budgets.show": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.edit": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.update": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.destroy": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.store": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.update": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        },
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.destroy": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        },
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.chat": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.scan-ticket": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "subscription.checkout": [
        {
            "name": "plan",
            "required": true
        }
    ],
    "billing.success": [],
    "billing.cancel": [],
    "plans": [],
    "subscription.manage": [],
    "subscription.swap": [
        {
            "name": "plan",
            "required": true
        }
    ],
    "subscription.cancel": [],
    "subscription.resume": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
